# aaxine
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aaxine.1.gz
complete -c aaxine -s h -l help -d 'Show summary of options and available output drivers (plugins)'
complete -c aaxine -s A -l audio-driver -d 'Use given audio driver.  Available drivers can be listed with "aaxine --help"'
complete -c aaxine -s a -l audio-channel -d 'Use given audio channel'
complete -c aaxine -s R -l recognize-by -d 'Determine the method used to recognize stream type.  Possible options are:'

