# chwb2
# Autogenerated from man page /usr/lib/jvm/default/man/man1/chwb2.1.gz
complete -c chwb2 -s I
complete -c chwb2 -s O -d 'Set the inner/outer border color of wid to color'
complete -c chwb2 -s i
complete -c chwb2 -s o -d 'Sets the inner/outer border width of wid to size'

