# dqtool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dqtool.1.gz
complete -c dqtool -l debug -s d
complete -c dqtool -l help -s h
complete -c dqtool -l template -s t
complete -c dqtool -l verbose -s v
complete -c dqtool -l version -s V

