# lqtplay
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lqtplay.1.gz
complete -c lqtplay -o noxv -d 'Don\'t use the Xvideo extension for accelerated video playback (YUV->RGB color…'
complete -c lqtplay -o nogl -d 'Don\'t use OpenGL (via GLX extension) for video scaling'
complete -c lqtplay -o noalsa -d 'Don\'t use Alsa for audio output'

