# mapw
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mapw.1.gz
complete -c mapw -s m -d 'Map (show) wid'
complete -c mapw -s t -d 'Toggle wid Ns \\(cqs visibility'
complete -c mapw -s u -d 'Unmap (hide) wid'

