# pdbtool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pdbtool.1.gz
complete -c pdbtool -l dump-tags -s T
complete -c pdbtool -l pdb -s p
complete -c pdbtool -l program -s P
complete -c pdbtool -l debug -s d
complete -c pdbtool -l program-tree
complete -c pdbtool -l verbose -s v
complete -c pdbtool -l color-out -s c
complete -c pdbtool -l debug-csv -s C
complete -c pdbtool -l debug-pattern -d 'option as comma-separated values'
complete -c pdbtool -s D
complete -c pdbtool -l file -s f
complete -c pdbtool -l filter -s F
complete -c pdbtool -l message -s M
complete -c pdbtool -l template
complete -c pdbtool -l directory
complete -c pdbtool -l glob -s G
complete -c pdbtool -l recursive -s r
complete -c pdbtool -l iterate-outliers -s o
complete -c pdbtool -l named-parsers -s n
complete -c pdbtool -l no-parse
complete -c pdbtool -l samples
complete -c pdbtool -l support -s S
complete -c pdbtool -l rule-id
complete -c pdbtool -l validate

