# recountdiff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/recountdiff.1.gz
complete -c recountdiff -l help -d 'Display a short usage message'
complete -c recountdiff -l version -d 'Display the version number of recountdiff'

