# rediff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rediff.1.gz
complete -c rediff -l help -d 'Display a short usage message'
complete -c rediff -l version -d 'Display the version number of rediff'

