# slogverify
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slogverify.1.gz
complete -c slogverify -l iterative -s i -d 'Iterative mode'
complete -c slogverify -l key-file -s k -d 'The initial host key (k0).  This option is used in normal mode only'
complete -c slogverify -l mac-file -s m -d 'The current MAC file used'
complete -c slogverify -l prev-key-file -s p -d 'The host key corresponding to the previous log file'
complete -c slogverify -l prev-mac-file -s r -d 'The MAC file from the previous log file'
complete -c slogverify -l help -s h -d 'Display a help message'

