# slogencrypt
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slogencrypt.1.gz
complete -c slogencrypt -l key-file -s k -d 'The current host key from the system where the encryption will be performed'
complete -c slogencrypt -l mac-file -s m -d 'The current MAC file from the system where the encryption will be performed'
complete -c slogencrypt -l help -s h -d 'Display a help message'

