# slogkey
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slogkey.1.gz
complete -c slogkey -l master-key -s m -d 'Generates a mew master key'
complete -c slogkey -l derive-key -s d -d 'Derive a host key using a previously generated master key'
complete -c slogkey -l counter -s c -d 'Display the current log sequence counter of a key'
complete -c slogkey -l help -s h -d 'Display a help message'

