# syslog-ng-ctl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/syslog-ng-ctl.1.gz
complete -c syslog-ng-ctl -l stderr -d or
complete -c syslog-ng-ctl -s e -d 'option, the messages will be sent to stderr'
complete -c syslog-ng-ctl -l control -s c
complete -c syslog-ng-ctl -l reset -s r

