# syslog-ng-debun
# Autogenerated from man page /usr/lib/jvm/default/man/man1/syslog-ng-debun.1.gz
complete -c syslog-ng-debun -s r
complete -c syslog-ng-debun -s h
complete -c syslog-ng-debun -s l
complete -c syslog-ng-debun -s d
complete -c syslog-ng-debun -s R
complete -c syslog-ng-debun -s W
complete -c syslog-ng-debun -o Fedv -l enable-core -d options
complete -c syslog-ng-debun -s D
complete -c syslog-ng-debun -s t
complete -c syslog-ng-debun -s w
complete -c syslog-ng-debun -s s
complete -c syslog-ng-debun -s i
complete -c syslog-ng-debun -s p
complete -c syslog-ng-debun -s P
complete -c syslog-ng-debun -o Fev -d 'syslog-ng-debun -r -p -d -w 5 -t 10 Collect pcap and debug mode output follow…'

