# terminator
# Autogenerated from man page /usr/share/man/man1/terminator.1.gz
complete -c terminator -s M -l maximize -d 'Start with a maximized window'
complete -c terminator -l execute2
complete -c terminator -l new-tab -d 'If this is specified and Terminator is already running, DBus will be used to …'

