# xine-remote
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xine-remote.1.gz
complete -c xine-remote -s H -l host -d 'Try to connect <hostname>'
complete -c xine-remote -s P -l port -d 'Try to connect the host using <port>'
complete -c xine-remote -s c -l command -d 'Send <command> to server then quit'
complete -c xine-remote -s n -l noconnect -d 'Do not initiate the connection on startup'
complete -c xine-remote -s v -l version -d 'Display version'
complete -c xine-remote -s h -l help -d 'Display options summary'

