# xine-check
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xine-check.1.gz
complete -c xine-check -s h -l help -d 'Show summary of options and version number'
complete -c xine-check -s q -l quiet -d 'Only give a single one-line messages, even if problems are found'
complete -c xine-check -s v -l verbose -d 'Enable extended output describing each check in detail, which produces a kind…'
complete -c xine-check -s B -l batch -d 'Turn off pause after long messages'
complete -c xine-check -s b -l bug -d 'Produce a bug report.  This is the same as calling xine-bugreport directly'

